###  Q1 Most viewed Videos on YouTube

In [1]:
#Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
#Rank, Name, Artist, Upload date, Views

import selenium
from selenium import webdriver
import pandas as pd
import warnings
warnings.filterwarnings("ignore")
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.service import Service

import time
from selenium.common.exceptions import NoSuchElementException


driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url='https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)
driver.maximize_window()

In [2]:
rank=[]

try:
    rank_tag = driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]")
    for i in rank_tag:
        rank.append(i.text.split('.')[0])
        
except NoSuchElementException:    
    rank.append('-')
except StaleElementReferenceException:
    rank.append('-')

name=[]

try:
    name_tag = driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]")
    for i in name_tag:
        name.append(i.text.split('"')[1])
        
except NoSuchElementException:    
    name.append('-')
except StaleElementReferenceException:
    name.append('-')

artist=[]

try:
    artist_tag = driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]")
    for i in artist_tag:
        artist.append(i.text)
        
except NoSuchElementException:    
    artist.append('-')
except StaleElementReferenceException:
    artist.append('-')

views=[]

try:
    view_tag = driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]")
    for i in view_tag:
        views.append(i.text)
        
except NoSuchElementException:    
    views.append('-')
except StaleElementReferenceException:
    views.append('-')

    
date=[]

try:
    date_tag = driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]")
    for i in date_tag:
        date.append(i.text)
        
except NoSuchElementException:    
    date.append('-')
except StaleElementReferenceException:
    date.append('-')

    
videos={'Rank':rank,'Name':name,'Artist':artist,
        'Views':views,'Date':date}
videos=pd.DataFrame(data=videos)
videos

,Rank,Name,Artist,Views,Date
0,1,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,11.05,"June 17, 2016"
1,2,Despacito,Luis Fonsi,7.93,"January 12, 2017"
2,3,Johny Johny Yes Papa,LooLoo Kids,6.40,"October 8, 2016"
3,4,Shape of You,Ed Sheeran,5.77,"January 30, 2017"
4,5,See You Again,Wiz Khalifa,5.59,"April 6, 2015"
5,6,Bath Song,Cocomelon – Nursery Rhymes,5.54,"May 2, 2018"
6,7,Phonics Song with Two Words,ChuChu TV,4.77,"March 6, 2014"
7,8,Uptown Funk,Mark Ronson,4.65,"November 19, 2014"
8,9,Learning Colors – Colorful Eggs on a Farm,Miroshka TV,4.60,"February 27, 2018"
9,10,Masha and the Bear – Recipe for Disaster,Get Movies,4.50,"January 31, 2012"
10,11,Gangnam Style,Psy,4.50,"July 15, 2012"
11,12,Wheels on the Bus,Cocomelon – Nursery Rhymes,4.24,"May 24, 2018"
12,13,Dame Tu Cosita,El Chombo,4.00,"April 5, 2018"
13,14,Sugar,Maroon 5,3.74,"January 14, 2015"
14,15,Roar,Katy Perry,3.63,"September 5, 2013"
15,16,Counting Stars,OneRepublic,3.62,"May 31, 2013"
16,17,Sorry,Justin Bieber,3.57,"October 22, 2015"
17,18,Thinking Out Loud,Ed Sheeran,3.48,"October 7, 2014"
18,19,Axel F,Crazy Frog,3.45,"June 16, 2009"
19,20,Dark Horse,Katy Perry,3.32,"February 20, 2014"
20,21,Girls Like You,Maroon 5,3.32,"May 31, 2018"
21,22,Faded,Alan Walker,3.32,"December 3, 2015"
22,23,Baa Baa Black Sheep,Cocomelon – Nursery Rhymes,3.31,"June 25, 2018"
23,24,Let Her Go,Passenger,3.27,"July 25, 2012"
24,25,Bailando,Enrique Iglesias,3.25,"April 11, 2014"
25,26,Lean On,Major Lazer,3.24,"March 22, 2015"
26,27,Perfect,Ed Sheeran,3.22,"November 9, 2017"
27,28,Waka Waka (This Time for Africa),Shakira,3.21,"June 4, 2010"
28,29,Shake It Off,Taylor Swift,3.19,"August 18, 2014"
29,30,Mi Gente,J Balvin,3.11,"June 29, 2017"

In [3]:
driver.close

### 2. Team India’s international fixtures from bcci.tv.

In [4]:
driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url='http://www.bcci.tv/'
driver.get(url)
driver.maximize_window()

In [5]:
intn_btn = driver.find_element(By.XPATH,"//li[@class='nav-item']/a")
intn_btn.click()

In [33]:
series=[]
ser_tag=driver.find_elements(By.XPATH,"//h5[@class='fix-text']//span")

for i in ser_tag:
    series.append(i.text)

match=[]
mat_tag=driver.find_elements(By.XPATH,"//span[@class='matchOrderText ng-binding ng-scope']")

for i in mat_tag:
    match.append(i.text.split('-')[0])
    
place=[]
plac_tag=driver.find_elements(By.XPATH,"//span[@class='ng-binding ng-scope']")

for i in plac_tag:
    place.append(i.text)

date=[]
dat_tag=driver.find_elements(By.XPATH,"//h5[@class='ng-binding']")

for i in dat_tag:
    date.append(i.text)

time=[]
tim_tag=driver.find_elements(By.XPATH,"//h5[@class='text-right ng-binding']")

for i in tim_tag:
    time.append(i.text)

matches={'Match':match,'Series':series[1:10:2],'Place':place,
        'Date':date,'Time':time}
matches=pd.DataFrame(data=matches)
matches

,Match,Series,Place,Date,Time
0,1st ODI,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club,",18 AUG 2022,12:45 PM IST
1,2nd ODI,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club,",20 AUG 2022,12:45 PM IST
2,3rd ODI,INDIA TOUR OF ZIMBABWE ODI SERIES 2022,"Harare Sports Club,",22 AUG 2022,12:45 PM IST
3,1st T20I,ASIA CUP 2022,"Dubai International Cricket Stadium,",28 AUG 2022,7:30 PM IST
4,2nd T20I,ASIA CUP 2022,"Dubai International Cricket Stadium,",31 AUG 2022,7:30 PM IST

In [34]:
driver.close

### 3. Details of selenium exception from guru99.com.

In [2]:
driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url='http://www.guru99.com/'
driver.get(url)
driver.maximize_window()

In [4]:
search_bar= driver.find_element(By.XPATH,"//input[@class='gsc-input']")
search_bar.send_keys('Selenium Exception Handling')

In [5]:
search_btn = driver.find_element(By.XPATH,"//button[@class='gsc-search-button gsc-search-button-v2']")
search_btn.click()

In [6]:
site = driver.find_element(By.XPATH,"//div[@class='gs-title']//a")
site.click()

In [7]:
url = driver.find_element(By.XPATH,"//div[@class='gs-title']//a")
page_url=url.get_attribute("href")
driver.get(page_url)

In [11]:
name=[]
    
name_tag = driver.find_elements(By.XPATH,"//table[@class='table table-striped']//tr//td[1]")
for i in name_tag:
    name.append(i.text)

descp=[]
    
des_tag = driver.find_elements(By.XPATH,"//table[@class='table table-striped']//tr//td[2]")
for i in des_tag:
    descp.append(i.text)
df={'Name':name,'Description':descp}
df=pd.DataFrame(data=df)
df

,Name,Description
0,ElementNotVisibleException,This type of Selenium exception occurs when an...
1,ElementNotSelectableException,This Selenium exception occurs when an element...
2,NoSuchElementException,This Exception occurs if an element could not ...
3,NoSuchFrameException,This Exception occurs if the frame target to b...
4,NoAlertPresentException,This Exception occurs when you switch to no pr...
5,NoSuchWindowException,This Exception occurs if the window target to ...
6,StaleElementReferenceException,This Selenium exception occurs happens when th...
7,SessionNotFoundException,The WebDriver is acting after you quit the bro...
8,TimeoutException,Thrown when there is not enough time for a com...
9,WebDriverException,This Exception takes place when the WebDriver ...
10,ConnectionClosedException,This type of Exception takes place when there ...
11,ElementClickInterceptedException,The command may not be completed as the elemen...
12,ElementNotInteractableException,This Selenium exception is thrown when any ele...
13,ErrorInResponseException,This happens while interacting with the Firefo...
14,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if ...
15,ImeActivationFailedException,This expectation will occur when IME engine ac...
16,ImeNotAvailableException,It takes place when IME support is unavailable.
17,InsecureCertificateException,Navigation made the user agent to hit a certif...
18,InvalidArgumentException,It occurs when an argument does not belong to ...
19,InvalidCookieDomainException,This happens when you try to add a cookie unde...
20,InvalidCoordinatesException,This type of Exception matches an interacting ...
21,InvalidElementStateExceptio,It occurs when command can’t be finished when ...
22,InvalidSessionIdException,This Exception took place when the given sessi...
23,InvalidSwitchToTargetException,This occurs when the frame or window target to...
24,JavascriptException,This issue occurs while executing JavaScript g...
25,JsonException,It occurs when you afford to get the session w...
26,NoSuchAttributeException,This kind of Exception occurs when the attribu...
27,MoveTargetOutOfBoundsException,It takes place if the target provided to the A...
28,NoSuchContextException,ContextAware does mobile device testing.
29,NoSuchCookieException,This Exception occurs when no cookie matching ...
30,NotFoundException,This Exception is a subclass of WebDriverExcep...
31,RemoteDriverServerException,This Selenium exception is thrown when the ser...
32,ScreenshotException,It is not possible to capture a screen.
33,SessionNotCreatedException,It happens when a new session could not be suc...
34,UnableToSetCookieException,This occurs if a driver is unable to set a coo...
35,UnexpectedTagNameException,Happens if a support class did not get a web e...
36,UnhandledAlertException,This expectation occurs when there is an alert...
37,UnexpectedAlertPresentException,It occurs when there is the appearance of an u...
38,UnknownMethodException,This Exception happens when the requested comm...
39,UnreachableBrowserException,This Exception occurs only when the browser is...
40,UnsupportedCommandException,This occurs when remote WebDriver does n’t sen...

In [12]:
driver.close

### 4.  State-wise GDP of India from statisticstime.com.

In [114]:
import requests
from bs4 import BeautifulSoup
driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url = "https://statisticstimes.com/"
page = requests.get(url)
print("Legality Response number from our URL is:", page) # to show the response output from the webpage
soup = BeautifulSoup(page.content)

driver.get(url)
driver.maximize_window()

Legality Response number from our URL is: <Response [200]>

In [115]:

economy = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/button')
economy.click()
time.sleep(2)
india = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]')
india.click()
time.sleep(2)

In [116]:

# Empty lists
Rank = []
State = []
GSDP1 = []
GSDP2  = []
Share = []
GDP_billion = []

try: # Scraping Rank
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping Name
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException as e:
    print("No such element present")
    
try: # Scraping GSDP1
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException as e:
    print("-")
    
try: # Scraping GSDP2
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException as e:
    print("-")

try: # Scraping share
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException as e:
    print("-")    
    
try: # Scraping GDP billion
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException as e:
    print("-")
    
# Creating data frame 
stats = pd.DataFrame({"Rank":Rank, "State":State, "GSDP (Cr INR at Current prices) (19-20)":GSDP1,
                      "GSDP (Cr INR at Current prices) (18-19)":GSDP2, "Share (18-19)":Share, 
                      "GDP ($ billion)":GDP_billion})
stats

Empty DataFrame
Columns: [Rank, State, GSDP (Cr INR at Current prices) (19-20), GSDP (Cr INR at Current prices) (18-19), Share (18-19), GDP ($ billion)]
Index: []

### 6. Top 100 songs on billiboard.com

In [2]:
driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url='https://www.billboard.com/'
driver.get(url)
driver.maximize_window()

In [4]:
top_btn = driver.find_element(By.XPATH,"//li[@class='o-nav__list-item ']//a")
top_btn.click()

In [12]:
song=[]
song_tag=driver.find_elements(By.XPATH,"//li[@class='lrv-u-width-100p']//h3")
for i in song_tag:
    song.append(i.text)

artist=[]
art_tag=driver.find_elements(By.XPATH,"//li[@class='lrv-u-width-100p']//span")
for i in art_tag:
    artist.append(i.text)
#artist[::7][:100]

lastweek=[]
las_tag=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']//span")
for i in las_tag:
    lastweek.append(i.text)
#lastweek[::2][:100]

peak =[]
peak_tag=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max']//span")
for i in peak_tag:
    peak.append(i.text)

weeks=[]
week_tag=driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']//span")
for i in week_tag:
    weeks.append(i.text)
#weeks[1::2][:100]

hot100 = {'Song':song,'Artist':artist[::7][:100],'LastWeek':lastweek[::2][:100],
          'Peakposition':peak,'WeeksonChart':weeks[1::2][:100]}
hot100=pd.DataFrame(data=hot100)
hot100

,Song,Artist,LastWeek,Peakposition,WeeksonChart
0,Break My Soul,Beyonce,6,1,7
1,About Damn Time,Lizzo,1,1,16
2,As It Was,Harry Styles,2,1,18
3,Running Up That Hill (A Deal With God),Kate Bush,3,3,30
4,Wait For U,Future Featuring Drake & Tems,5,1,14
...,...,...,...,...,...
95,Until I Found You,Stephen Sanchez,88,88,5
96,Un Ratito,Bad Bunny,93,16,13
97,Best Thing Since Backroads,Jake Owen,72,72,4
98,La Corriente,Bad Bunny & Tony Dize,100,32,10
99,"Bzrp Music Sessions, Vol. 52",Bizarrap & Quevedo,98,98,2

### 9. most watched tv series of all time from imdb.com

In [14]:
driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url='http://www.imdb.com/list/ls095964455/'
driver.get(url)
driver.maximize_window()

In [19]:
name=[]
year=[]
genre=[]
rating=[]
runtime=[]
votes=[]

nam_tag = driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//h3//a")
for i in nam_tag:
    name.append(i.text)
    
year_tag = driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//h3//span[2]")
for i in year_tag:
    year.append(i.text)

gen_tag = driver.find_elements(By.XPATH,"//p[@class='text-muted text-small']//span[5]")
for i in gen_tag:
    genre.append(i.text)
    
runt_tag = driver.find_elements(By.XPATH,"//p[@class='text-muted text-small']//span[3]")
for i in runt_tag:
    runtime.append(i.text)

ratg_tag = driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']//span[2]")
for i in ratg_tag:
    rating.append(i.text)

vot_tag = driver.find_elements(By.XPATH,"//p[@class='text-muted text-small']//span[2]")
for i in vot_tag:
    votes.append(i.text)
#votes[1::2][:100]

topser = {'Name':name,'Year':year,'Genre':genre,
          'RunTime':runtime,'Rating':rating,'Votes':votes[1::2][:100]}
topser =pd.DataFrame(data=topser)
topser

,Name,Year,Genre,RunTime,Rating,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,021,423"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,117,881"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.2,"959,790"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"286,929"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"246,530"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,268"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"60,163"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"193,412"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"40,808"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"233,376"

In [20]:
driver.close

### 8. Highest Selling Novels

In [21]:
driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url='https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)
driver.maximize_window()

In [28]:
book = []
author = []
volume =[]
publisher=[]
genres=[]

book_tag = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']//tbody//tr//td[2]")
for i in book_tag:
    book.append(i.text)
author_tag = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']//tbody//tr//td[3]")
for i in author_tag:
    author.append(i.text)
volume_tag = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']//tbody//tr//td[4]")
for i in volume_tag:
    volume.append(i.text)
pub_tag = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']//tbody//tr//td[5]")
for i in pub_tag:
    publisher.append(i.text)
gen_tag = driver.find_elements(By.XPATH,"//table[@class='in-article sortable']//tbody//tr//td[6]")
for i in gen_tag:
    genres.append(i.text)


novel = {'Book':book,'Author':author,'Volume':volume,
          'Publisher':publisher,'Genre':genres}
novel =pd.DataFrame(data=novel)
novel

,Book,Author,Volume,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [29]:
driver.close

### 7. Data science recruiters from naukri.com.

In [30]:
driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url='https://www.naukri.com/hr-recruiters-consultants'
driver.get(url)
driver.maximize_window()

In [31]:
search_btn = driver.find_element(By.XPATH,"//input[@class='sugInp']")
search_btn.send_keys('Data Science')

sech_btn = driver.find_element(By.XPATH,"//button[@class='fl qsbSrch blueBtn']")
sech_btn.click()

In [46]:
names=[]
desig=[]
comp=[]
skills=[]
locatn=[]

rec_name=driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']")
for i in rec_name:
    names.append(i.text)
des=driver.find_elements(By.XPATH,"//span[@class='ellipsis clr']")
for i in des:
    desig.append(i.text)
com=driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]//a[2]")
for i in com:
    comp.append(i.text)
skil=driver.find_elements(By.XPATH,"//div[@class='hireSec highlightable']")
for i in skil:
    skills.append(i.text)
loc=driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]//span")
for i in loc:
    locatn.append(i.text)
#len(locatn[2::3][:50])

naukri = {'Name':names[:49],'Designation':desig[:49],'Company':comp[:49],
          'Skills':skills[:49],'Location':locatn[2::3][:50]}
naukri =pd.DataFrame(data=naukri)
naukri

,Name,Designation,Company,Skills,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Prof...",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration...",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine...",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, We...",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architec...",UK - (london)
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,"Analytics, Business Intelligence, Business Ana...",Vadodara / Baroda
6,Institute for Financial Management and Resear,Programme Manager,IFMR,Data Science,Chennai
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,"Machine Learning, algorithms, Go Getter, Compu...",Trivandrum
8,Asif Lucknowi,Director,Weupskill- Live Wire India,"Technical Training, Software Development, Pres...",Indore
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,"Software Development, It Sales, Account Manage...",Bengaluru / Bangalore
10,Vaishnavi Kudalkar,HR Executive,Codeachive learning,"Data Science, Python, Data Analytics",Mumbai
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,"Oracle Dba, Data Science, Data Warehousing, ET...",Hyderabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,"Qa, Ui/ux, Java Developer, Java Architect, C++...",Hyderabad / Secunderabad
13,Mubarak,Company HR,MoneyTap,"Business Intelligence, Data Warehousing, Data ...",Bengaluru / Bangalore
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,"Office Administration, Hr Administration, tele...",Mumbai
15,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,"Social Media, digital media maketing, seo, smm...",Hyderabad / Secunderabad
16,Kapil Devang,HR Manager,BISP Solutions,"Big Data, Hadoop, Data Analytics, Data Science",Bhopal
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,"React.js, Data Science, Java, Front End, Busin...",Chandigarh
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,"Qlikview, Qlik Sense, Microsoft Azure, Power B...",Pune
19,Manisha Yadav,HR Executive,Easi Tax,"Telecalling, Client Interaction, Marketing, Re...",Navi Mumbai
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Data Science,Cochin
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,"Corporate Sales, Software Development, Softwar...",Delhi
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,"Data Analytics, Data Science, Machine Learning...",Hyderabad / Secunderabad
23,Rithika dadwal,HR Recruiter,Affine Analytics,"Data Science, Machine Learning, Python, R, Dee...",Pune
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,"Big Data, Data Science, Artificial Intelligenc...",Pune
25,Shaun Rao,Manager Human Resources,Exela Technologies,"Java, Net, Angularjs, Hr, Infrastructure, Mana...",Pune
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,"Data Science, Artificial Intelligence, Machine...",Pune
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,"Software Architecture, Vp Engineering, Product...",Bengaluru / Bangalore
28,kumar,Proprietor,trainin,"Data Science, Hadoop, Rpas, Devops, Python, Aw...",Bengaluru / Bangalore
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,"Signal Processing, Machine Learning, Neural Ne...",Rajat Kumar
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,"Web Technologies, Project Management, Software...",Dhruv Dev Dubey
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,"Server Administartion, Verilog, Vhdl, Digital ...",Jayanth N
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd","Data Analytics, Managed Services, Team Leading...",Avodha
33,Avodha,Business Development Associate,Nikitha Palaparthi,"Ethical Hacking, Security Operations Center, S...",Priya Khare
34,Priya Khare,Senior Manager,Independent Consultant,"Data Science, Artificial Intelligence, analyti...",Amit Sharma
35,Amit Sharma,Consultant,ASCO consulting,"Machine Learning, Artificial Intelligence, Dat...",Kanan
36,Kanan,senior technology instructor,NY INST,"C, C++, Artificial Intelligence, Python, Php, ...",Shashikant Chaudhary
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,"Relationship Management, Retail Sales, Private...",Brad
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,"Data Science, Software Engineering",Rutuja Pawar
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,"Data Science, Big Data Analytics, Digital Mark...",Madhusudhan Sridhar
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,"Data Science, Recruitment, Salary",Ankit Sinha
41,Ankit Sinha,Head Analytics,Suntech Global,"B.Tech, Tableau, Statistics, R, Analytics, Tim...",Gaurav Chouhan
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,"Software Development, Business Intelligence, B...",Rashi Kacker
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,"Data Science, Node.js, Angularjs",Ashwini
44,Ashwini,Director Global Delivery,MRP Advisers,"Data Science, Media Marketing, Resource Planni...",Balaji Kolli
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,"Data Analysis, Learning, Data Science, Compute...",Rajani Nagaraj
46,Rajani Nagaraj,HR Manager,WildJasmine,"Java, Hadoop, R, Machine Learning, Spark, Flum...",ROHIT Kumar
47,ROHIT Kumar,Architect,LNT Private Limited,"Software Development, Core Java, Unit Testing,...",Amir Chowdhury
48,Amir Chowdhury,Managing Partner,Granular.ai,"Machine Learning, Data Science, Product Manage...",Recruitment Manager

In [47]:

driver.close

### 10. Details of Datasets from UCI machine learning repositories

In [67]:
driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url='https://archive.ics.uci.edu/'
driver.get(url)
driver.maximize_window()

In [68]:
#url for view datasets
dataurl = driver.find_element(By.XPATH,"//span[@class='normal']//b//a")
url1=dataurl.get_attribute("href")
driver.get(url1)

In [82]:
name=[]
try:
    names=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]/table/tbody/tr/td[2]/p/b/a")
    for i in names:
        name.append(i.text)
except NoSuchElementException:#handling no such element exception
    name.append('No details available')
time.sleep(2)

#scraping data type
data_type=[]
try:
    datype=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]")
    for i in datype[1:]:
         data_type.append(i.text)
except NoSuchElementException:
    data_type.append("No information")
time.sleep(2)


#scraping dataset names
default_task=[]
try:
    deftas=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]")
    for i in deftas[1:]:
         default_task.append(i.text)
except NoSuchElementException:
    default_task.append("No information")
time.sleep(2)


#scraping dataset names
attr_type=[]
try:
    attrb=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]")
    for i in attrb[1:]:
         attr_type.append(i.text)
except NoSuchElementException:
    attr_type.append("No information")
time.sleep(2)


#scraping dataset names
no_of_instances=[]
try:
    inst=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]")
    for i in inst[1:]:
         no_of_instances.append(i.text)
except NoSuchElementException:
    no_of_instances.append("No information")
time.sleep(2)


#scraping dataset names
no_of_attributes=[]
try:
    noattr=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]")
    for i in noattr[1:]:
         no_of_attributes.append(i.text)
except NoSuchElementException:
    no_of_attributes.append("No information")
time.sleep(2)


#scraping dataset names
year=[]
try:
    yr_tg=driver.find_elements(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]")
    for i in yr_tg[1:]:
         year.append(i.text)
except NoSuchElementException:
    year.append("No information")
time.sleep(2)

#creating dataframe
df=pd.DataFrame({'Name':name,
                'Data_type':data_type,
                'Task':default_task,
                'Attribute_type':attr_type,
                'No_of_instances':no_of_instances,
                'No_of_attributes':no_of_attributes,
                'Year':year})
df

,Name,Data_type,Task,Attribute_type,No_of_instances,No_of_attributes,Year
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitte...,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobi...,Univariate,Regression,Real,4000,2,2021

In [83]:
driver.close

### 5. The details of trending repositories on Github.com.

In [90]:
driver = webdriver.Chrome(r'C:\Users\Jayasri\Downloads\chromedriver_win32\chromedriver.exe')
driver = webdriver.Chrome('chromedriver.exe')

url='https://github.com/'
driver.get(url)
driver.maximize_window()

In [94]:
exp_btn = driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details")
exp_btn.click()

In [96]:
trend_url = driver.find_element(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a")
urls=trend_url.get_attribute("href")
driver.get(urls)

In [117]:
# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

#scraping repositories urls
repos=driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']/a")
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2) 

    
#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    

for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
    #scraping repositories discription
    try:
        repo = driver.find_element(By.XPATH,"/html/body/div[4]/div/main/div[2]/div/div/div[2]/div[2]/div/div[1]/div/p")
        repo_desc.append(repo.text)
    except NoSuchElementException:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element(By.XPATH,"//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements(By.XPATH,"//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
#creating dataframe

In [ ]:
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

In [118]:
driver.close